/**
 * Serviço de persistência híbrido (Offline-First) para tarefas e demandas clínicas.
 * Utiliza o localStorage para leitura/escrita em tempo real (UI sem atrasos) e o Supabase
 * para persistência segura em nuvem e sincronização entre dispositivos.
 */
import { KEY_TASKS } from '../../../config/storageKeys.js';
import { getPresetDate } from '../domain/taskTypes.js';
import { SUPABASE_URL, SUPABASE_ANON_KEY } from '../../../config/env.js';

export const TASKS_UPDATED_EVENT = 'nutrisa_tasks_updated';

// Helpers de mapeamento entre JS (camelCase) e Supabase (snake_case)
function mapToDB(task) {
  return {
    id: task.id,
    title: task.title,
    patient_name: task.patientName || null,
    patient_phone: task.patientPhone || null,
    category: task.category,
    priority: task.priority,
    due_date: task.dueDate || null,
    status: task.status,
    notes: task.notes || null,
    calendar_event_id: task.calendarEventId || null,
    event_date: task.eventDate || null,
    auto_generated: Boolean(task.autoGenerated),
    created_at: task.createdAt,
    completed_at: task.completedAt || null,
    updated_at: task.updatedAt || new Date().toISOString()
  };
}

function mapToJS(row) {
  return {
    id: row.id,
    title: row.title,
    patientName: row.patient_name || '',
    patientPhone: row.patient_phone || '',
    category: row.category,
    priority: row.priority,
    dueDate: row.due_date,
    status: row.status,
    notes: row.notes || '',
    calendarEventId: row.calendar_event_id || null,
    eventDate: row.event_date || null,
    autoGenerated: row.auto_generated || false,
    createdAt: row.created_at,
    completedAt: row.completed_at || null,
    updatedAt: row.updated_at
  };
}

// Configuração padrão do fetch para o Supabase
const getSupabaseHeaders = () => ({
  'Content-Type': 'application/json',
  'apikey': SUPABASE_ANON_KEY,
  'Authorization': `Bearer ${SUPABASE_ANON_KEY}`
});

/**
 * Notifica ouvintes locais que as tarefas mudaram (para atualizar a UI imediatamente).
 */
function notifyUpdate() {
  if (typeof window !== 'undefined') {
    window.dispatchEvent(new CustomEvent(TASKS_UPDATED_EVENT));
  }
}

/**
 * Lê diretamente do cache local para resposta imediata da interface.
 */
export function getTasks() {
  if (typeof window === 'undefined') return [];
  try {
    const raw = localStorage.getItem(KEY_TASKS);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch (err) {
    console.error('Erro ao ler tarefas do localStorage:', err);
    return [];
  }
}

/**
 * Salva apenas no cache local. (Usado internamente e durante a sincronização).
 */
function saveTasksToLocal(tasks) {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(KEY_TASKS, JSON.stringify(tasks));
    notifyUpdate();
  } catch (err) {
    console.error('Erro ao salvar tarefas no localStorage:', err);
  }
}

/**
 * Sincroniza a lista inteira puxando do Supabase. Atualiza o cache se a nuvem tiver novidades.
 */
export async function syncTasksFromCloud() {
  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) return;
  try {
    const response = await fetch(`${SUPABASE_URL}/rest/v1/nutrisa_tasks?select=*&order=created_at.desc`, {
      method: 'GET',
      headers: getSupabaseHeaders()
    });
    
    if (response.ok) {
      const data = await response.json();
      const jsTasks = data.map(mapToJS);
      saveTasksToLocal(jsTasks);
    }
  } catch (err) {
    console.error('Falha ao sincronizar tarefas da nuvem:', err);
  }
}

/**
 * Gera UUID V4 compatível com o Supabase.
 */
function generateUUID() {
  if (typeof crypto !== 'undefined' && crypto.randomUUID) {
    return crypto.randomUUID();
  }
  return '10000000-1000-4000-8000-100000000000'.replace(/[018]/g, c =>
    (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16)
  );
}

/**
 * Cria uma nova tarefa localmente e envia para a nuvem.
 */
export function createTask(taskData) {
  const newTask = {
    id: generateUUID(),
    title: taskData.title?.trim() || 'Nova Demanda',
    patientName: taskData.patientName?.trim() || '',
    patientPhone: taskData.patientPhone?.trim() || '',
    category: taskData.category || 'geral',
    priority: taskData.priority || 'media',
    dueDate: taskData.dueDate || getPresetDate(0),
    status: 'pending',
    notes: taskData.notes?.trim() || '',
    calendarEventId: taskData.calendarEventId || null,
    eventDate: taskData.eventDate || null,
    autoGenerated: taskData.autoGenerated || false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    completedAt: null,
  };

  // 1. Otimista: Salva local e reflete na interface na hora
  const current = getTasks();
  saveTasksToLocal([newTask, ...current]);

  // 2. Assíncrono: Envia para a nuvem
  if (SUPABASE_URL && SUPABASE_ANON_KEY) {
    fetch(`${SUPABASE_URL}/rest/v1/nutrisa_tasks`, {
      method: 'POST',
      headers: getSupabaseHeaders(),
      body: JSON.stringify(mapToDB(newTask))
    }).then(async res => {
      if (!res.ok) {
        const error = await res.json();
        console.error('Falha ao salvar tarefa no Supabase (400):', error);
      }
    }).catch(err => console.error('Falha de rede ao salvar no Supabase:', err));
  }

  return newTask;
}

/**
 * Atualiza campos de uma tarefa existente (Otimista + Sincronização).
 */
export function updateTask(taskId, updates) {
  const current = getTasks();
  let updatedTask = null;

  const newTasks = current.map(task => {
    if (task.id === taskId) {
      updatedTask = { ...task, ...updates, updatedAt: new Date().toISOString() };
      return updatedTask;
    }
    return task;
  });

  // Salva local imediato
  saveTasksToLocal(newTasks);

  // Envia para a nuvem
  if (updatedTask && SUPABASE_URL && SUPABASE_ANON_KEY) {
    fetch(`${SUPABASE_URL}/rest/v1/nutrisa_tasks?id=eq.${taskId}`, {
      method: 'PATCH',
      headers: getSupabaseHeaders(),
      body: JSON.stringify(mapToDB(updatedTask))
    }).catch(err => console.error('Falha ao atualizar tarefa no Supabase:', err));
  }
}

/**
 * Alterna status e envia para a nuvem.
 */
export function toggleTaskStatus(taskId) {
  const current = getTasks();
  let updatedTask = null;

  const newTasks = current.map(task => {
    if (task.id === taskId) {
      const isCompleted = task.status === 'completed';
      updatedTask = {
        ...task,
        status: isCompleted ? 'pending' : 'completed',
        completedAt: isCompleted ? null : new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };
      return updatedTask;
    }
    return task;
  });

  saveTasksToLocal(newTasks);

  if (updatedTask && SUPABASE_URL && SUPABASE_ANON_KEY) {
    fetch(`${SUPABASE_URL}/rest/v1/nutrisa_tasks?id=eq.${taskId}`, {
      method: 'PATCH',
      headers: getSupabaseHeaders(),
      body: JSON.stringify(mapToDB(updatedTask))
    }).catch(err => console.error('Falha ao alternar status no Supabase:', err));
  }
}

/**
 * Remove uma tarefa localmente e na nuvem.
 */
export function deleteTask(taskId) {
  const current = getTasks();
  const updated = current.filter(task => task.id !== taskId);
  saveTasksToLocal(updated);

  if (SUPABASE_URL && SUPABASE_ANON_KEY) {
    fetch(`${SUPABASE_URL}/rest/v1/nutrisa_tasks?id=eq.${taskId}`, {
      method: 'DELETE',
      headers: getSupabaseHeaders()
    }).catch(err => console.error('Falha ao deletar tarefa no Supabase:', err));
  }
}

/**
 * Remove múltiplas tarefas localmente e na nuvem.
 */
export function deleteMultipleTasks(taskIds) {
  if (!taskIds || taskIds.length === 0) return;
  
  const current = getTasks();
  const updated = current.filter(task => !taskIds.includes(task.id));
  saveTasksToLocal(updated);

  if (SUPABASE_URL && SUPABASE_ANON_KEY) {
    const idList = taskIds.join(',');
    fetch(`${SUPABASE_URL}/rest/v1/nutrisa_tasks?id=in.(${idList})`, {
      method: 'DELETE',
      headers: getSupabaseHeaders()
    }).catch(err => console.error('Falha ao deletar múltiplas tarefas no Supabase:', err));
  }
}
