export const DEMO_EXTRACTED_DATA = {
  patient: {
    name: "Paciente de demonstração",
    age: "31 anos",
    gender: "Feminino",
    height: "1.53 m",
    weight: "64.7 kg",
    date: new Date().toLocaleDateString('pt-BR')
  },
  biaEquipment: "AvaBio 380 (Multifrequência Octopolar)",
  anthropometricMethod: "Protocolo Jackson & Pollock (7 Dobras)",
  metrics: [
    { key: "weight", title: "Peso Corporal", unit: "kg", biaValue: 64.7, adipometryValue: 64.7, selected: "bia", category: "Geral", idealMin: 45.0, idealMax: 58.0 },
    { key: "fatPercentage", title: "Percentual de Gordura (%G)", unit: "%", biaValue: 35.2, adipometryValue: 33.9, selected: "adipometry", category: "Composição", idealMin: 18.0, idealMax: 25.0 },
    { key: "fatMass", title: "Massa Gorda", unit: "kg", biaValue: 22.7, adipometryValue: 21.9, selected: "adipometry", category: "Composição", idealMin: 9.0, idealMax: 15.0 },
    { key: "leanMass", title: "Massa Magra / Livre de Gordura", unit: "kg", biaValue: 42.0, adipometryValue: 42.8, selected: "adipometry", category: "Composição", idealMin: 38.0, idealMax: 48.0 },
    { key: "skeletalMuscle", title: "Massa Muscular Esquelética (SMM)", unit: "kg", biaValue: 23.5, adipometryValue: 24.0, selected: "bia", category: "Músculo", idealMin: 20.0, idealMax: 27.0 },
    { key: "residualMass", title: "Massa Residual", unit: "kg", biaValue: null, adipometryValue: 13.5, selected: "adipometry", category: "Composição", idealMin: 10.0, idealMax: 15.0 },
    { key: "boneMineral", title: "Massa Mineral / Óssea", unit: "kg", biaValue: 2.45, adipometryValue: null, selected: "bia", category: "Composição", idealMin: 2.10, idealMax: 2.90 },
    { key: "totalBodyWater", title: "Água Corporal Total (ACT)", unit: "L", biaValue: 31.2, adipometryValue: null, selected: "bia", category: "Hidratação", idealMin: 28.0, idealMax: 36.0 },
    { key: "icw", title: "Água Intracelular (AIC / ICW)", unit: "L", biaValue: 19.5, adipometryValue: null, selected: "bia", category: "Hidratação", idealMin: 17.0, idealMax: 22.0 },
    { key: "ecw", title: "Água Extracelular (AEC / ECW)", unit: "L", biaValue: 11.7, adipometryValue: null, selected: "bia", category: "Hidratação", idealMin: 10.0, idealMax: 14.0 },
    { key: "visceralFatLevel", title: "Nível de Gordura Visceral", unit: "Nível", biaValue: 5, adipometryValue: null, selected: "bia", category: "Risco Metabólico", idealMin: 1, idealMax: 9 },
    { key: "bmr", title: "Taxa Metabólica Basal (TMB)", unit: "kcal", biaValue: 1310, adipometryValue: 1295, selected: "adipometry", category: "Metabolismo", idealMin: 1200, idealMax: 1500 },
    { key: "metabolicAge", title: "Idade Metabólica", unit: "anos", biaValue: 28, adipometryValue: null, selected: "bia", category: "Metabolismo", idealMin: 18, idealMax: 31 },
    { key: "bmi", title: "Índice de Massa Corporal (IMC)", unit: "kg/m²", biaValue: 27.6, adipometryValue: 27.6, selected: "bia", category: "Geral", idealMin: 18.5, idealMax: 24.9 },
    { key: "waistHipRatio", title: "Relação Cintura/Quadril (RCQ)", unit: "", biaValue: null, adipometryValue: 0.82, selected: "adipometry", category: "Risco Metabólico", idealMin: 0.70, idealMax: 0.85 },
    { key: "skinfoldSum", title: "Somatório de Dobras", unit: "mm", biaValue: null, adipometryValue: 209.5, selected: "adipometry", category: "Dobras", idealMin: 60.0, idealMax: 140.0 },
    { key: "bodyDensity", title: "Densidade Corporal", unit: "g/mL", biaValue: null, adipometryValue: 1.020, selected: "adipometry", category: "Composição", idealMin: 1.030, idealMax: 1.060 }
  ],
  skinfolds: [
    { site: "Tríceps", value: 35.0 },
    { site: "Bicipital", value: 10.0 },
    { site: "Subescapular", value: 32.0 },
    { site: "Axilar Média", value: 16.0 },
    { site: "Suprailíaca", value: 35.0 },
    { site: "Abdomen", value: 30.0 },
    { site: "Coxa Média", value: 40.5 },
    { site: "Torácica / Peitoral", value: 21.0 }
  ],
  circumferences: [
    { site: "Ombro", value: 109.0 },
    { site: "Tórax", value: 100.0 },
    { site: "Cintura", value: 83.5 },
    { site: "Quadril", value: 102.0 },
    { site: "Abdomen", value: 87.0 },
    { site: "Braço Relaxado", value: 33.0 },
    { site: "Coxa Medial", value: 55.5 },
    { site: "Panturrilha", value: 37.0 }
  ],
  segmental: {
    rightArm: { leanMass: 2.15, leanMassRatio: 102, fatMass: 1.80, fatMassRatio: 115 },
    leftArm: { leanMass: 2.10, leanMassRatio: 100, fatMass: 1.70, fatMassRatio: 112 },
    trunk: { leanMass: 18.60, leanMassRatio: 100, fatMass: 3.50, fatMassRatio: 105 },
    rightLeg: { leanMass: 6.40, leanMassRatio: 98, fatMass: 4.90, fatMassRatio: 120 },
    leftLeg: { leanMass: 6.30, leanMassRatio: 97, fatMass: 4.80, fatMassRatio: 118 }
  },
  history: [
    {
      date: "10/01/2026",
      weight: 68.5,
      fatPercentage: 38.5,
      fatMass: 26.4,
      leanMass: 42.1,
      skeletalMuscle: 23.1,
      totalBodyWater: 30.1,
      icw: 18.8,
      ecw: 11.3,
      visceralFatLevel: 7,
      bmr: 1280,
      metabolicAge: 33,
      bmi: 29.2,
      waistHipRatio: 0.85,
      skinfoldSum: 245.0,
      waist: 88.0,
      abdomen: 92.0,
      hip: 106.0,
      bodyDensity: 1.012
    },
    {
      date: "15/03/2026",
      weight: 67.0,
      fatPercentage: 36.8,
      fatMass: 24.6,
      leanMass: 42.4,
      skeletalMuscle: 23.4,
      totalBodyWater: 30.5,
      icw: 19.0,
      ecw: 11.5,
      visceralFatLevel: 6,
      bmr: 1288,
      metabolicAge: 31,
      bmi: 28.6,
      waistHipRatio: 0.84,
      skinfoldSum: 230.0,
      waist: 86.0,
      abdomen: 90.0,
      hip: 104.5,
      bodyDensity: 1.015
    },
    {
      date: "20/05/2026",
      weight: 65.8,
      fatPercentage: 35.2,
      fatMass: 23.1,
      leanMass: 42.7,
      skeletalMuscle: 23.8,
      totalBodyWater: 30.9,
      icw: 19.3,
      ecw: 11.6,
      visceralFatLevel: 6,
      bmr: 1292,
      metabolicAge: 29,
      bmi: 28.1,
      waistHipRatio: 0.83,
      skinfoldSum: 218.0,
      waist: 84.5,
      abdomen: 88.5,
      hip: 103.0,
      bodyDensity: 1.018
    }
  ],
  aiAnalysisText: "A paciente apresenta evolução positiva com redução no percentual de gordura (33.9%) e preservação da massa magra (42.8 kg). A relação cintura/quadril (0.82) indica evolução no perfil de risco metabólico. Nível de hidratação celular satisfatório e Ângulo de Fase dentro do padrão para o perfil."
};
